include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    non_abstract_class_inherits_abstract_member: ignore

linter:
  rules:
    public_member_api_docs: false
    eol_at_end_of_file: false